apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80 # You can use port 80 here for HTTP traffic
      targetPort: 80 # This should match the port your Node.js application is running on (80)
  type: LoadBalancer
